name = "ten-worker-cua-ban"
main = "server.js"
compatibility_date = "2024-04-03"
compatibility_flags = [ "nodejs_compat" ]

# Nếu bạn có biến môi trường (API_KEY, DATABASE_URL...), hãy để ở đây
[vars]
NODE_VERSION = "20"
